tcp---dynamic1----adhoc01---tmpdmesg.txt 0
tcp---dynamic1----adhoc02---tmpdmesg.txt 0
tcp---dynamic1----adhoc03---tmpdmesg.txt 0
tcp---dynamic1----adhoc04---tmpdmesg.txt 460
tcp---dynamic1----adhoc05---tmpdmesg.txt 454
tcp---dynamic1----adhoc06---tmpdmesg.txt 339
tcp---dynamic1----adhoc07---tmpdmesg.txt 0
tcp---dynamic1----adhoc08---tmpdmesg.txt 0
tcp---dynamic1----adhoc09---tmpdmesg.txt 0
tcp---dynamic1----AP1---tmpdmesg.txt 504
tcp---dynamic1----AP2---tmpdmesg.txt 0
tcp---dynamic1----flyNode01---tmpdmesg.txt 55
tcp---dynamic1----flyNode02---tmpdmesg.txt 62
tcp---dynamic1----flyNode03---tmpdmesg.txt 0
tcp---dynamic1----flyNode04---tmpdmesg.txt 0
tcp---dynamic1----gateway---tmpdmesg.txt 502
tcp---dynamic2----adhoc01---tmpdmesg.txt 0
tcp---dynamic2----adhoc02---tmpdmesg.txt 11
tcp---dynamic2----adhoc03---tmpdmesg.txt 0
tcp---dynamic2----adhoc04---tmpdmesg.txt 105
tcp---dynamic2----adhoc05---tmpdmesg.txt 135
tcp---dynamic2----adhoc06---tmpdmesg.txt 260
tcp---dynamic2----adhoc07---tmpdmesg.txt 0
tcp---dynamic2----adhoc08---tmpdmesg.txt 17
tcp---dynamic2----adhoc09---tmpdmesg.txt 0
tcp---dynamic2----AP1---tmpdmesg.txt 382
tcp---dynamic2----AP2---tmpdmesg.txt 18
tcp---dynamic2----flyNode01---tmpdmesg.txt 0
tcp---dynamic2----flyNode02---tmpdmesg.txt 244
tcp---dynamic2----flyNode03---tmpdmesg.txt 0
tcp---dynamic2----flyNode04---tmpdmesg.txt 0
tcp---dynamic2----gateway---tmpdmesg.txt 398
tcp---static----adhoc01---tmpdmesg.txt 0
tcp---static----adhoc02---tmpdmesg.txt 0
tcp---static----adhoc03---tmpdmesg.txt 0
tcp---static----adhoc04---tmpdmesg.txt 423
tcp---static----adhoc05---tmpdmesg.txt 426
tcp---static----adhoc06---tmpdmesg.txt 273
tcp---static----adhoc07---tmpdmesg.txt 0
tcp---static----adhoc08---tmpdmesg.txt 0
tcp---static----adhoc09---tmpdmesg.txt 0
tcp---static----AP1---tmpdmesg.txt 434
tcp---static----AP2---tmpdmesg.txt 0
tcp---static----flyNode01---tmpdmesg.txt 11
tcp---static----flyNode02---tmpdmesg.txt 11
tcp---static----flyNode03---tmpdmesg.txt 0
tcp---static----flyNode04---tmpdmesg.txt 0
tcp---static----gateway---tmpdmesg.txt 432
mptcp-balia---static----adhoc01---tmpdmesg.txt 0
mptcp-balia---static----adhoc02---tmpdmesg.txt 0
mptcp-balia---static----adhoc03---tmpdmesg.txt 0
mptcp-balia---static----adhoc04---tmpdmesg.txt 386
mptcp-balia---static----adhoc05---tmpdmesg.txt 410
mptcp-balia---static----adhoc06---tmpdmesg.txt 415
mptcp-balia---static----adhoc07---tmpdmesg.txt 0
mptcp-balia---static----adhoc08---tmpdmesg.txt 0
mptcp-balia---static----adhoc09---tmpdmesg.txt 0
mptcp-balia---static----AP1---tmpdmesg.txt 392
mptcp-balia---static----AP2---tmpdmesg.txt 20
mptcp-balia---static----flyNode01---tmpdmesg.txt 12
mptcp-balia---static----flyNode02---tmpdmesg.txt 0
mptcp-balia---static----flyNode03---tmpdmesg.txt 14
mptcp-balia---static----flyNode04---tmpdmesg.txt 4
mptcp-balia---static----gateway---tmpdmesg.txt 410
mptcp-bbr---static----adhoc01---tmpdmesg.txt 0
mptcp-bbr---static----adhoc02---tmpdmesg.txt 0
mptcp-bbr---static----adhoc03---tmpdmesg.txt 0
mptcp-bbr---static----adhoc04---tmpdmesg.txt 175
mptcp-bbr---static----adhoc05---tmpdmesg.txt 242
mptcp-bbr---static----adhoc06---tmpdmesg.txt 258
mptcp-bbr---static----adhoc07---tmpdmesg.txt 0
mptcp-bbr---static----adhoc08---tmpdmesg.txt 0
mptcp-bbr---static----adhoc09---tmpdmesg.txt 0
mptcp-bbr---static----AP1---tmpdmesg.txt 216
mptcp-bbr---static----AP2---tmpdmesg.txt 9
mptcp-bbr---static----flyNode01---tmpdmesg.txt 41
mptcp-bbr---static----flyNode02---tmpdmesg.txt 0
mptcp-bbr---static----flyNode03---tmpdmesg.txt 9
mptcp-bbr---static----flyNode04---tmpdmesg.txt 0
mptcp-bbr---static----gateway---tmpdmesg.txt 222
mptcp-blest---static----adhoc01---tmpdmesg.txt 2
mptcp-blest---static----adhoc02---tmpdmesg.txt 2
mptcp-blest---static----adhoc03---tmpdmesg.txt 0
mptcp-blest---static----adhoc04---tmpdmesg.txt 330
mptcp-blest---static----adhoc05---tmpdmesg.txt 348
mptcp-blest---static----adhoc06---tmpdmesg.txt 402
mptcp-blest---static----adhoc07---tmpdmesg.txt 0
mptcp-blest---static----adhoc08---tmpdmesg.txt 0
mptcp-blest---static----adhoc09---tmpdmesg.txt 0
mptcp-blest---static----AP1---tmpdmesg.txt 334
mptcp-blest---static----AP2---tmpdmesg.txt 39
mptcp-blest---static----flyNode01---tmpdmesg.txt 2
mptcp-blest---static----flyNode02---tmpdmesg.txt 2
mptcp-blest---static----flyNode03---tmpdmesg.txt 39
mptcp-blest---static----flyNode04---tmpdmesg.txt 39
mptcp-blest---static----gateway---tmpdmesg.txt 368
mptcp-cubic---static----adhoc01---tmpdmesg.txt 0
mptcp-cubic---static----adhoc02---tmpdmesg.txt 0
mptcp-cubic---static----adhoc03---tmpdmesg.txt 0
mptcp-cubic---static----adhoc04---tmpdmesg.txt 296
mptcp-cubic---static----adhoc05---tmpdmesg.txt 340
mptcp-cubic---static----adhoc06---tmpdmesg.txt 349
mptcp-cubic---static----adhoc07---tmpdmesg.txt 0
mptcp-cubic---static----adhoc08---tmpdmesg.txt 0
mptcp-cubic---static----adhoc09---tmpdmesg.txt 0
mptcp-cubic---static----AP1---tmpdmesg.txt 335
mptcp-cubic---static----AP2---tmpdmesg.txt 1
mptcp-cubic---static----flyNode01---tmpdmesg.txt 39
mptcp-cubic---static----flyNode02---tmpdmesg.txt 0
mptcp-cubic---static----flyNode03---tmpdmesg.txt 1
mptcp-cubic---static----flyNode04---tmpdmesg.txt 0
mptcp-cubic---static----gateway---tmpdmesg.txt 333
mptcp-ecf---static----adhoc01---tmpdmesg.txt 0
mptcp-ecf---static----adhoc02---tmpdmesg.txt 0
mptcp-ecf---static----adhoc03---tmpdmesg.txt 0
mptcp-ecf---static----adhoc04---tmpdmesg.txt 124
mptcp-ecf---static----adhoc05---tmpdmesg.txt 166
mptcp-ecf---static----adhoc06---tmpdmesg.txt 238
mptcp-ecf---static----adhoc07---tmpdmesg.txt 0
mptcp-ecf---static----adhoc08---tmpdmesg.txt 0
mptcp-ecf---static----adhoc09---tmpdmesg.txt 0
mptcp-ecf---static----AP1---tmpdmesg.txt 202
mptcp-ecf---static----AP2---tmpdmesg.txt 16
mptcp-ecf---static----flyNode01---tmpdmesg.txt 94
mptcp-ecf---static----flyNode02---tmpdmesg.txt 59
mptcp-ecf---static----flyNode03---tmpdmesg.txt 3
mptcp-ecf---static----flyNode04---tmpdmesg.txt 0
mptcp-ecf---static----gateway---tmpdmesg.txt 215
mptcp-olia---static----adhoc01---tmpdmesg.txt 0
mptcp-olia---static----adhoc02---tmpdmesg.txt 2
mptcp-olia---static----adhoc03---tmpdmesg.txt 2
mptcp-olia---static----adhoc04---tmpdmesg.txt 424
mptcp-olia---static----adhoc05---tmpdmesg.txt 450
mptcp-olia---static----adhoc06---tmpdmesg.txt 495
mptcp-olia---static----adhoc07---tmpdmesg.txt 0
mptcp-olia---static----adhoc08---tmpdmesg.txt 0
mptcp-olia---static----adhoc09---tmpdmesg.txt 0
mptcp-olia---static----AP1---tmpdmesg.txt 480
mptcp-olia---static----AP2---tmpdmesg.txt 0
mptcp-olia---static----flyNode01---tmpdmesg.txt 56
mptcp-olia---static----flyNode02---tmpdmesg.txt 37
mptcp-olia---static----flyNode03---tmpdmesg.txt 0
mptcp-olia---static----flyNode04---tmpdmesg.txt 0
mptcp-olia---static----gateway---tmpdmesg.txt 478
mptcp-red---static----adhoc01---tmpdmesg.txt 0
mptcp-red---static----adhoc02---tmpdmesg.txt 0
mptcp-red---static----adhoc03---tmpdmesg.txt 0
mptcp-red---static----adhoc04---tmpdmesg.txt 450
mptcp-red---static----adhoc05---tmpdmesg.txt 486
mptcp-red---static----adhoc06---tmpdmesg.txt 502
mptcp-red---static----adhoc07---tmpdmesg.txt 0
mptcp-red---static----adhoc08---tmpdmesg.txt 0
mptcp-red---static----adhoc09---tmpdmesg.txt 0
mptcp-red---static----AP1---tmpdmesg.txt 467
mptcp-red---static----AP2---tmpdmesg.txt 4
mptcp-red---static----flyNode01---tmpdmesg.txt 17
mptcp-red---static----flyNode02---tmpdmesg.txt 0
mptcp-red---static----flyNode03---tmpdmesg.txt 4
mptcp-red---static----flyNode04---tmpdmesg.txt 1
mptcp-red---static----gateway---tmpdmesg.txt 468
mptcp-rr---static----adhoc01---tmpdmesg.txt 23
mptcp-rr---static----adhoc02---tmpdmesg.txt 23
mptcp-rr---static----adhoc03---tmpdmesg.txt 23
mptcp-rr---static----adhoc04---tmpdmesg.txt 183
mptcp-rr---static----adhoc05---tmpdmesg.txt 235
mptcp-rr---static----adhoc06---tmpdmesg.txt 286
mptcp-rr---static----adhoc07---tmpdmesg.txt 0
mptcp-rr---static----adhoc08---tmpdmesg.txt 0
mptcp-rr---static----adhoc09---tmpdmesg.txt 0
mptcp-rr---static----AP1---tmpdmesg.txt 245
mptcp-rr---static----AP2---tmpdmesg.txt 21
mptcp-rr---static----flyNode01---tmpdmesg.txt 49
mptcp-rr---static----flyNode02---tmpdmesg.txt 5
mptcp-rr---static----flyNode03---tmpdmesg.txt 11
mptcp-rr---static----flyNode04---tmpdmesg.txt 11
mptcp-rr---static----gateway---tmpdmesg.txt 263
mptcp-balia---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc04---tmpdmesg.txt 453
mptcp-balia---dynamic1----adhoc05---tmpdmesg.txt 459
mptcp-balia---dynamic1----adhoc06---tmpdmesg.txt 461
mptcp-balia---dynamic1----adhoc07---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-balia---dynamic1----AP1---tmpdmesg.txt 456
mptcp-balia---dynamic1----AP2---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode01---tmpdmesg.txt 6
mptcp-balia---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-balia---dynamic1----gateway---tmpdmesg.txt 452
mptcp-bbr---dynamic1----adhoc01---tmpdmesg.txt 6
mptcp-bbr---dynamic1----adhoc02---tmpdmesg.txt 6
mptcp-bbr---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-bbr---dynamic1----adhoc04---tmpdmesg.txt 140
mptcp-bbr---dynamic1----adhoc05---tmpdmesg.txt 176
mptcp-bbr---dynamic1----adhoc06---tmpdmesg.txt 180
mptcp-bbr---dynamic1----adhoc07---tmpdmesg.txt 35
mptcp-bbr---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-bbr---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-bbr---dynamic1----AP1---tmpdmesg.txt 143
mptcp-bbr---dynamic1----AP2---tmpdmesg.txt 35
mptcp-bbr---dynamic1----flyNode01---tmpdmesg.txt 0
mptcp-bbr---dynamic1----flyNode02---tmpdmesg.txt 3
mptcp-bbr---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-bbr---dynamic1----flyNode04---tmpdmesg.txt 1
mptcp-bbr---dynamic1----gateway---tmpdmesg.txt 175
mptcp-blest---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc04---tmpdmesg.txt 239
mptcp-blest---dynamic1----adhoc05---tmpdmesg.txt 445
mptcp-blest---dynamic1----adhoc06---tmpdmesg.txt 462
mptcp-blest---dynamic1----adhoc07---tmpdmesg.txt 28
mptcp-blest---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-blest---dynamic1----AP1---tmpdmesg.txt 392
mptcp-blest---dynamic1----AP2---tmpdmesg.txt 38
mptcp-blest---dynamic1----flyNode01---tmpdmesg.txt 172
mptcp-blest---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-blest---dynamic1----flyNode03---tmpdmesg.txt 6
mptcp-blest---dynamic1----flyNode04---tmpdmesg.txt 1
mptcp-blest---dynamic1----gateway---tmpdmesg.txt 427
mptcp-cubic---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc04---tmpdmesg.txt 243
mptcp-cubic---dynamic1----adhoc05---tmpdmesg.txt 288
mptcp-cubic---dynamic1----adhoc06---tmpdmesg.txt 289
mptcp-cubic---dynamic1----adhoc07---tmpdmesg.txt 29
mptcp-cubic---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc09---tmpdmesg.txt 1
mptcp-cubic---dynamic1----AP1---tmpdmesg.txt 226
mptcp-cubic---dynamic1----AP2---tmpdmesg.txt 47
mptcp-cubic---dynamic1----flyNode01---tmpdmesg.txt 3
mptcp-cubic---dynamic1----flyNode02---tmpdmesg.txt 1
mptcp-cubic---dynamic1----flyNode03---tmpdmesg.txt 1
mptcp-cubic---dynamic1----flyNode04---tmpdmesg.txt 1
mptcp-cubic---dynamic1----gateway---tmpdmesg.txt 269
mptcp-ecf---dynamic1----adhoc01---tmpdmesg.txt 3
mptcp-ecf---dynamic1----adhoc02---tmpdmesg.txt 3
mptcp-ecf---dynamic1----adhoc03---tmpdmesg.txt 3
mptcp-ecf---dynamic1----adhoc04---tmpdmesg.txt 306
mptcp-ecf---dynamic1----adhoc05---tmpdmesg.txt 316
mptcp-ecf---dynamic1----adhoc06---tmpdmesg.txt 383
mptcp-ecf---dynamic1----adhoc07---tmpdmesg.txt 3
mptcp-ecf---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-ecf---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-ecf---dynamic1----AP1---tmpdmesg.txt 313
mptcp-ecf---dynamic1----AP2---tmpdmesg.txt 30
mptcp-ecf---dynamic1----flyNode01---tmpdmesg.txt 30
mptcp-ecf---dynamic1----flyNode02---tmpdmesg.txt 14
mptcp-ecf---dynamic1----flyNode03---tmpdmesg.txt 27
mptcp-ecf---dynamic1----flyNode04---tmpdmesg.txt 27
mptcp-ecf---dynamic1----gateway---tmpdmesg.txt 340
mptcp-olia---dynamic1----adhoc01---tmpdmesg.txt 7
mptcp-olia---dynamic1----adhoc02---tmpdmesg.txt 2
mptcp-olia---dynamic1----adhoc03---tmpdmesg.txt 2
mptcp-olia---dynamic1----adhoc04---tmpdmesg.txt 613
mptcp-olia---dynamic1----adhoc05---tmpdmesg.txt 624
mptcp-olia---dynamic1----adhoc06---tmpdmesg.txt 693
mptcp-olia---dynamic1----adhoc07---tmpdmesg.txt 4
mptcp-olia---dynamic1----adhoc08---tmpdmesg.txt 4
mptcp-olia---dynamic1----adhoc09---tmpdmesg.txt 4
mptcp-olia---dynamic1----AP1---tmpdmesg.txt 647
mptcp-olia---dynamic1----AP2---tmpdmesg.txt 5
mptcp-olia---dynamic1----flyNode01---tmpdmesg.txt 34
mptcp-olia---dynamic1----flyNode02---tmpdmesg.txt 23
mptcp-olia---dynamic1----flyNode03---tmpdmesg.txt 1
mptcp-olia---dynamic1----flyNode04---tmpdmesg.txt 1
mptcp-olia---dynamic1----gateway---tmpdmesg.txt 649
mptcp-red---dynamic1----adhoc01---tmpdmesg.txt 11
mptcp-red---dynamic1----adhoc02---tmpdmesg.txt 11
mptcp-red---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc04---tmpdmesg.txt 484
mptcp-red---dynamic1----adhoc05---tmpdmesg.txt 536
mptcp-red---dynamic1----adhoc06---tmpdmesg.txt 617
mptcp-red---dynamic1----adhoc07---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-red---dynamic1----AP1---tmpdmesg.txt 531
mptcp-red---dynamic1----AP2---tmpdmesg.txt 18
mptcp-red---dynamic1----flyNode01---tmpdmesg.txt 41
mptcp-red---dynamic1----flyNode02---tmpdmesg.txt 32
mptcp-red---dynamic1----flyNode03---tmpdmesg.txt 18
mptcp-red---dynamic1----flyNode04---tmpdmesg.txt 18
mptcp-red---dynamic1----gateway---tmpdmesg.txt 547
mptcp-rr---dynamic1----adhoc01---tmpdmesg.txt 2
mptcp-rr---dynamic1----adhoc02---tmpdmesg.txt 2
mptcp-rr---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc04---tmpdmesg.txt 307
mptcp-rr---dynamic1----adhoc05---tmpdmesg.txt 316
mptcp-rr---dynamic1----adhoc06---tmpdmesg.txt 324
mptcp-rr---dynamic1----adhoc07---tmpdmesg.txt 2
mptcp-rr---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-rr---dynamic1----AP1---tmpdmesg.txt 308
mptcp-rr---dynamic1----AP2---tmpdmesg.txt 6
mptcp-rr---dynamic1----flyNode01---tmpdmesg.txt 2
mptcp-rr---dynamic1----flyNode02---tmpdmesg.txt 2
mptcp-rr---dynamic1----flyNode03---tmpdmesg.txt 4
mptcp-rr---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-rr---dynamic1----gateway---tmpdmesg.txt 309
mptcp-balia---dynamic2----adhoc01---tmpdmesg.txt 36
mptcp-balia---dynamic2----adhoc02---tmpdmesg.txt 34
mptcp-balia---dynamic2----adhoc03---tmpdmesg.txt 8
mptcp-balia---dynamic2----adhoc04---tmpdmesg.txt 141
mptcp-balia---dynamic2----adhoc05---tmpdmesg.txt 154
mptcp-balia---dynamic2----adhoc06---tmpdmesg.txt 286
mptcp-balia---dynamic2----adhoc07---tmpdmesg.txt 1
mptcp-balia---dynamic2----adhoc08---tmpdmesg.txt 1
mptcp-balia---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-balia---dynamic2----AP1---tmpdmesg.txt 256
mptcp-balia---dynamic2----AP2---tmpdmesg.txt 9
mptcp-balia---dynamic2----flyNode01---tmpdmesg.txt 9
mptcp-balia---dynamic2----flyNode02---tmpdmesg.txt 114
mptcp-balia---dynamic2----flyNode03---tmpdmesg.txt 8
mptcp-balia---dynamic2----flyNode04---tmpdmesg.txt 41
mptcp-balia---dynamic2----gateway---tmpdmesg.txt 261
mptcp-bbr---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc02---tmpdmesg.txt 3
mptcp-bbr---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc04---tmpdmesg.txt 82
mptcp-bbr---dynamic2----adhoc05---tmpdmesg.txt 109
mptcp-bbr---dynamic2----adhoc06---tmpdmesg.txt 470
mptcp-bbr---dynamic2----adhoc07---tmpdmesg.txt 92
mptcp-bbr---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-bbr---dynamic2----AP1---tmpdmesg.txt 363
mptcp-bbr---dynamic2----AP2---tmpdmesg.txt 58
mptcp-bbr---dynamic2----flyNode01---tmpdmesg.txt 36
mptcp-bbr---dynamic2----flyNode02---tmpdmesg.txt 278
mptcp-bbr---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-bbr---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-bbr---dynamic2----gateway---tmpdmesg.txt 418
mptcp-blest---dynamic2----adhoc01---tmpdmesg.txt 8
mptcp-blest---dynamic2----adhoc02---tmpdmesg.txt 8
mptcp-blest---dynamic2----adhoc03---tmpdmesg.txt 8
mptcp-blest---dynamic2----adhoc04---tmpdmesg.txt 249
mptcp-blest---dynamic2----adhoc05---tmpdmesg.txt 272
mptcp-blest---dynamic2----adhoc06---tmpdmesg.txt 394
mptcp-blest---dynamic2----adhoc07---tmpdmesg.txt 1
mptcp-blest---dynamic2----adhoc08---tmpdmesg.txt 23
mptcp-blest---dynamic2----adhoc09---tmpdmesg.txt 31
mptcp-blest---dynamic2----AP1---tmpdmesg.txt 313
mptcp-blest---dynamic2----AP2---tmpdmesg.txt 23
mptcp-blest---dynamic2----flyNode01---tmpdmesg.txt 8
mptcp-blest---dynamic2----flyNode02---tmpdmesg.txt 4
mptcp-blest---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-blest---dynamic2----flyNode04---tmpdmesg.txt 1
mptcp-blest---dynamic2----gateway---tmpdmesg.txt 334
mptcp-cubic---dynamic2----adhoc01---tmpdmesg.txt 33
mptcp-cubic---dynamic2----adhoc02---tmpdmesg.txt 33
mptcp-cubic---dynamic2----adhoc03---tmpdmesg.txt 33
mptcp-cubic---dynamic2----adhoc04---tmpdmesg.txt 287
mptcp-cubic---dynamic2----adhoc05---tmpdmesg.txt 369
mptcp-cubic---dynamic2----adhoc06---tmpdmesg.txt 430
mptcp-cubic---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-cubic---dynamic2----adhoc08---tmpdmesg.txt 48
mptcp-cubic---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-cubic---dynamic2----AP1---tmpdmesg.txt 306
mptcp-cubic---dynamic2----AP2---tmpdmesg.txt 61
mptcp-cubic---dynamic2----flyNode01---tmpdmesg.txt 19
mptcp-cubic---dynamic2----flyNode02---tmpdmesg.txt 0
mptcp-cubic---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-cubic---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-cubic---dynamic2----gateway---tmpdmesg.txt 363
mptcp-ecf---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-ecf---dynamic2----adhoc02---tmpdmesg.txt 30
mptcp-ecf---dynamic2----adhoc03---tmpdmesg.txt 21
mptcp-ecf---dynamic2----adhoc04---tmpdmesg.txt 225
mptcp-ecf---dynamic2----adhoc05---tmpdmesg.txt 226
mptcp-ecf---dynamic2----adhoc06---tmpdmesg.txt 474
mptcp-ecf---dynamic2----adhoc07---tmpdmesg.txt 20
mptcp-ecf---dynamic2----adhoc08---tmpdmesg.txt 6
mptcp-ecf---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-ecf---dynamic2----AP1---tmpdmesg.txt 419
mptcp-ecf---dynamic2----AP2---tmpdmesg.txt 17
mptcp-ecf---dynamic2----flyNode01---tmpdmesg.txt 21
mptcp-ecf---dynamic2----flyNode02---tmpdmesg.txt 213
mptcp-ecf---dynamic2----flyNode03---tmpdmesg.txt 3
mptcp-ecf---dynamic2----flyNode04---tmpdmesg.txt 3
mptcp-ecf---dynamic2----gateway---tmpdmesg.txt 434
mptcp-olia---dynamic2----adhoc01---tmpdmesg.txt 3
mptcp-olia---dynamic2----adhoc02---tmpdmesg.txt 23
mptcp-olia---dynamic2----adhoc03---tmpdmesg.txt 18
mptcp-olia---dynamic2----adhoc04---tmpdmesg.txt 274
mptcp-olia---dynamic2----adhoc05---tmpdmesg.txt 305
mptcp-olia---dynamic2----adhoc06---tmpdmesg.txt 608
mptcp-olia---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-olia---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-olia---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-olia---dynamic2----AP1---tmpdmesg.txt 553
mptcp-olia---dynamic2----AP2---tmpdmesg.txt 1
mptcp-olia---dynamic2----flyNode01---tmpdmesg.txt 14
mptcp-olia---dynamic2----flyNode02---tmpdmesg.txt 98
mptcp-olia---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-olia---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-olia---dynamic2----gateway---tmpdmesg.txt 551
mptcp-red---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc02---tmpdmesg.txt 18
mptcp-red---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc04---tmpdmesg.txt 188
mptcp-red---dynamic2----adhoc05---tmpdmesg.txt 202
mptcp-red---dynamic2----adhoc06---tmpdmesg.txt 328
mptcp-red---dynamic2----adhoc07---tmpdmesg.txt 7
mptcp-red---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-red---dynamic2----AP1---tmpdmesg.txt 297
mptcp-red---dynamic2----AP2---tmpdmesg.txt 1
mptcp-red---dynamic2----flyNode01---tmpdmesg.txt 0
mptcp-red---dynamic2----flyNode02---tmpdmesg.txt 67
mptcp-red---dynamic2----flyNode03---tmpdmesg.txt 1
mptcp-red---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-red---dynamic2----gateway---tmpdmesg.txt 296
mptcp-rr---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-rr---dynamic2----adhoc02---tmpdmesg.txt 0
mptcp-rr---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-rr---dynamic2----adhoc04---tmpdmesg.txt 288
mptcp-rr---dynamic2----adhoc05---tmpdmesg.txt 294
mptcp-rr---dynamic2----adhoc06---tmpdmesg.txt 324
mptcp-rr---dynamic2----adhoc07---tmpdmesg.txt 1
mptcp-rr---dynamic2----adhoc08---tmpdmesg.txt 8
mptcp-rr---dynamic2----adhoc09---tmpdmesg.txt 11
mptcp-rr---dynamic2----AP1---tmpdmesg.txt 278
mptcp-rr---dynamic2----AP2---tmpdmesg.txt 8
mptcp-rr---dynamic2----flyNode01---tmpdmesg.txt 0
mptcp-rr---dynamic2----flyNode02---tmpdmesg.txt 10
mptcp-rr---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-rr---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-rr---dynamic2----gateway---tmpdmesg.txt 283
dmptcp---dynamic1----adhoc01---tmpdmesg.txt 9
dmptcp---dynamic1----adhoc02---tmpdmesg.txt 9
dmptcp---dynamic1----adhoc03---tmpdmesg.txt 9
dmptcp---dynamic1----adhoc04---tmpdmesg.txt 207
dmptcp---dynamic1----adhoc05---tmpdmesg.txt 211
dmptcp---dynamic1----adhoc06---tmpdmesg.txt 222
dmptcp---dynamic1----adhoc07---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc08---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc09---tmpdmesg.txt 0
dmptcp---dynamic1----AP1---tmpdmesg.txt 220
dmptcp---dynamic1----AP2---tmpdmesg.txt 0
dmptcp---dynamic1----flyNode01---tmpdmesg.txt 5
dmptcp---dynamic1----flyNode02---tmpdmesg.txt 5
dmptcp---dynamic1----flyNode03---tmpdmesg.txt 0
dmptcp---dynamic1----flyNode04---tmpdmesg.txt 0
dmptcp---dynamic1----gateway---tmpdmesg.txt 217
dmptcp---dynamic2----adhoc01---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc02---tmpdmesg.txt 7
dmptcp---dynamic2----adhoc03---tmpdmesg.txt 7
dmptcp---dynamic2----adhoc04---tmpdmesg.txt 238
dmptcp---dynamic2----adhoc05---tmpdmesg.txt 251
dmptcp---dynamic2----adhoc06---tmpdmesg.txt 281
dmptcp---dynamic2----adhoc07---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc08---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc09---tmpdmesg.txt 0
dmptcp---dynamic2----AP1---tmpdmesg.txt 236
dmptcp---dynamic2----AP2---tmpdmesg.txt 12
dmptcp---dynamic2----flyNode01---tmpdmesg.txt 24
dmptcp---dynamic2----flyNode02---tmpdmesg.txt 21
dmptcp---dynamic2----flyNode03---tmpdmesg.txt 0
dmptcp---dynamic2----flyNode04---tmpdmesg.txt 0
dmptcp---dynamic2----gateway---tmpdmesg.txt 245
dmptcp---static----adhoc01---tmpdmesg.txt 0
dmptcp---static----adhoc02---tmpdmesg.txt 0
dmptcp---static----adhoc03---tmpdmesg.txt 0
dmptcp---static----adhoc04---tmpdmesg.txt 215
dmptcp---static----adhoc05---tmpdmesg.txt 219
dmptcp---static----adhoc06---tmpdmesg.txt 225
dmptcp---static----adhoc07---tmpdmesg.txt 0
dmptcp---static----adhoc08---tmpdmesg.txt 0
dmptcp---static----adhoc09---tmpdmesg.txt 0
dmptcp---static----AP1---tmpdmesg.txt 213
dmptcp---static----AP2---tmpdmesg.txt 0
dmptcp---static----flyNode01---tmpdmesg.txt 0
dmptcp---static----flyNode02---tmpdmesg.txt 0
dmptcp---static----flyNode03---tmpdmesg.txt 0
dmptcp---static----flyNode04---tmpdmesg.txt 0
dmptcp---static----gateway---tmpdmesg.txt 211
