tcp---dynamic1----adhoc01---tmpdmesg.txt 0
tcp---dynamic1----adhoc02---tmpdmesg.txt 0
tcp---dynamic1----adhoc03---tmpdmesg.txt 0
tcp---dynamic1----adhoc04---tmpdmesg.txt 0
tcp---dynamic1----adhoc05---tmpdmesg.txt 0
tcp---dynamic1----adhoc06---tmpdmesg.txt 0
tcp---dynamic1----adhoc07---tmpdmesg.txt 0
tcp---dynamic1----adhoc08---tmpdmesg.txt 0
tcp---dynamic1----adhoc09---tmpdmesg.txt 0
tcp---dynamic1----AP1---tmpdmesg.txt 0
tcp---dynamic1----AP2---tmpdmesg.txt 0
tcp---dynamic1----flyNode01---tmpdmesg.txt 0
tcp---dynamic1----flyNode02---tmpdmesg.txt 0
tcp---dynamic1----flyNode03---tmpdmesg.txt 0
tcp---dynamic1----flyNode04---tmpdmesg.txt 0
tcp---dynamic1----gateway---tmpdmesg.txt 0
tcp---dynamic2----adhoc01---tmpdmesg.txt 0
tcp---dynamic2----adhoc02---tmpdmesg.txt 0
tcp---dynamic2----adhoc03---tmpdmesg.txt 0
tcp---dynamic2----adhoc04---tmpdmesg.txt 0
tcp---dynamic2----adhoc05---tmpdmesg.txt 0
tcp---dynamic2----adhoc06---tmpdmesg.txt 0
tcp---dynamic2----adhoc07---tmpdmesg.txt 0
tcp---dynamic2----adhoc08---tmpdmesg.txt 0
tcp---dynamic2----adhoc09---tmpdmesg.txt 0
tcp---dynamic2----AP1---tmpdmesg.txt 0
tcp---dynamic2----AP2---tmpdmesg.txt 0
tcp---dynamic2----flyNode01---tmpdmesg.txt 0
tcp---dynamic2----flyNode02---tmpdmesg.txt 0
tcp---dynamic2----flyNode03---tmpdmesg.txt 0
tcp---dynamic2----flyNode04---tmpdmesg.txt 0
tcp---dynamic2----gateway---tmpdmesg.txt 0
tcp---static----adhoc01---tmpdmesg.txt 0
tcp---static----adhoc02---tmpdmesg.txt 0
tcp---static----adhoc03---tmpdmesg.txt 0
tcp---static----adhoc04---tmpdmesg.txt 0
tcp---static----adhoc05---tmpdmesg.txt 0
tcp---static----adhoc06---tmpdmesg.txt 0
tcp---static----adhoc07---tmpdmesg.txt 0
tcp---static----adhoc08---tmpdmesg.txt 0
tcp---static----adhoc09---tmpdmesg.txt 0
tcp---static----AP1---tmpdmesg.txt 0
tcp---static----AP2---tmpdmesg.txt 0
tcp---static----flyNode01---tmpdmesg.txt 0
tcp---static----flyNode02---tmpdmesg.txt 0
tcp---static----flyNode03---tmpdmesg.txt 0
tcp---static----flyNode04---tmpdmesg.txt 0
tcp---static----gateway---tmpdmesg.txt 0
mptcp-balia---static----adhoc01---tmpdmesg.txt 0
mptcp-balia---static----adhoc02---tmpdmesg.txt 0
mptcp-balia---static----adhoc03---tmpdmesg.txt 0
mptcp-balia---static----adhoc04---tmpdmesg.txt 176
mptcp-balia---static----adhoc05---tmpdmesg.txt 189
mptcp-balia---static----adhoc06---tmpdmesg.txt 194
mptcp-balia---static----adhoc07---tmpdmesg.txt 0
mptcp-balia---static----adhoc08---tmpdmesg.txt 0
mptcp-balia---static----adhoc09---tmpdmesg.txt 0
mptcp-balia---static----AP1---tmpdmesg.txt 178
mptcp-balia---static----AP2---tmpdmesg.txt 11
mptcp-balia---static----flyNode01---tmpdmesg.txt 2
mptcp-balia---static----flyNode02---tmpdmesg.txt 0
mptcp-balia---static----flyNode03---tmpdmesg.txt 11
mptcp-balia---static----flyNode04---tmpdmesg.txt 2
mptcp-balia---static----gateway---tmpdmesg.txt 186
mptcp-bbr---static----adhoc01---tmpdmesg.txt 0
mptcp-bbr---static----adhoc02---tmpdmesg.txt 0
mptcp-bbr---static----adhoc03---tmpdmesg.txt 0
mptcp-bbr---static----adhoc04---tmpdmesg.txt 215
mptcp-bbr---static----adhoc05---tmpdmesg.txt 267
mptcp-bbr---static----adhoc06---tmpdmesg.txt 289
mptcp-bbr---static----adhoc07---tmpdmesg.txt 0
mptcp-bbr---static----adhoc08---tmpdmesg.txt 0
mptcp-bbr---static----adhoc09---tmpdmesg.txt 0
mptcp-bbr---static----AP1---tmpdmesg.txt 248
mptcp-bbr---static----AP2---tmpdmesg.txt 11
mptcp-bbr---static----flyNode01---tmpdmesg.txt 33
mptcp-bbr---static----flyNode02---tmpdmesg.txt 0
mptcp-bbr---static----flyNode03---tmpdmesg.txt 11
mptcp-bbr---static----flyNode04---tmpdmesg.txt 0
mptcp-bbr---static----gateway---tmpdmesg.txt 256
mptcp-blest---static----adhoc01---tmpdmesg.txt 0
mptcp-blest---static----adhoc02---tmpdmesg.txt 0
mptcp-blest---static----adhoc03---tmpdmesg.txt 0
mptcp-blest---static----adhoc04---tmpdmesg.txt 184
mptcp-blest---static----adhoc05---tmpdmesg.txt 190
mptcp-blest---static----adhoc06---tmpdmesg.txt 256
mptcp-blest---static----adhoc07---tmpdmesg.txt 0
mptcp-blest---static----adhoc08---tmpdmesg.txt 0
mptcp-blest---static----adhoc09---tmpdmesg.txt 0
mptcp-blest---static----AP1---tmpdmesg.txt 184
mptcp-blest---static----AP2---tmpdmesg.txt 30
mptcp-blest---static----flyNode01---tmpdmesg.txt 0
mptcp-blest---static----flyNode02---tmpdmesg.txt 0
mptcp-blest---static----flyNode03---tmpdmesg.txt 30
mptcp-blest---static----flyNode04---tmpdmesg.txt 30
mptcp-blest---static----gateway---tmpdmesg.txt 212
mptcp-cubic---static----adhoc01---tmpdmesg.txt 0
mptcp-cubic---static----adhoc02---tmpdmesg.txt 0
mptcp-cubic---static----adhoc03---tmpdmesg.txt 0
mptcp-cubic---static----adhoc04---tmpdmesg.txt 203
mptcp-cubic---static----adhoc05---tmpdmesg.txt 226
mptcp-cubic---static----adhoc06---tmpdmesg.txt 256
mptcp-cubic---static----adhoc07---tmpdmesg.txt 0
mptcp-cubic---static----adhoc08---tmpdmesg.txt 0
mptcp-cubic---static----adhoc09---tmpdmesg.txt 0
mptcp-cubic---static----AP1---tmpdmesg.txt 219
mptcp-cubic---static----AP2---tmpdmesg.txt 0
mptcp-cubic---static----flyNode01---tmpdmesg.txt 16
mptcp-cubic---static----flyNode02---tmpdmesg.txt 0
mptcp-cubic---static----flyNode03---tmpdmesg.txt 0
mptcp-cubic---static----flyNode04---tmpdmesg.txt 0
mptcp-cubic---static----gateway---tmpdmesg.txt 217
mptcp-ecf---static----adhoc01---tmpdmesg.txt 0
mptcp-ecf---static----adhoc02---tmpdmesg.txt 0
mptcp-ecf---static----adhoc03---tmpdmesg.txt 0
mptcp-ecf---static----adhoc04---tmpdmesg.txt 223
mptcp-ecf---static----adhoc05---tmpdmesg.txt 253
mptcp-ecf---static----adhoc06---tmpdmesg.txt 348
mptcp-ecf---static----adhoc07---tmpdmesg.txt 0
mptcp-ecf---static----adhoc08---tmpdmesg.txt 0
mptcp-ecf---static----adhoc09---tmpdmesg.txt 0
mptcp-ecf---static----AP1---tmpdmesg.txt 301
mptcp-ecf---static----AP2---tmpdmesg.txt 28
mptcp-ecf---static----flyNode01---tmpdmesg.txt 103
mptcp-ecf---static----flyNode02---tmpdmesg.txt 96
mptcp-ecf---static----flyNode03---tmpdmesg.txt 4
mptcp-ecf---static----flyNode04---tmpdmesg.txt 0
mptcp-ecf---static----gateway---tmpdmesg.txt 326
mptcp-olia---static----adhoc01---tmpdmesg.txt 0
mptcp-olia---static----adhoc02---tmpdmesg.txt 0
mptcp-olia---static----adhoc03---tmpdmesg.txt 0
mptcp-olia---static----adhoc04---tmpdmesg.txt 262
mptcp-olia---static----adhoc05---tmpdmesg.txt 275
mptcp-olia---static----adhoc06---tmpdmesg.txt 320
mptcp-olia---static----adhoc07---tmpdmesg.txt 0
mptcp-olia---static----adhoc08---tmpdmesg.txt 0
mptcp-olia---static----adhoc09---tmpdmesg.txt 0
mptcp-olia---static----AP1---tmpdmesg.txt 294
mptcp-olia---static----AP2---tmpdmesg.txt 0
mptcp-olia---static----flyNode01---tmpdmesg.txt 37
mptcp-olia---static----flyNode02---tmpdmesg.txt 22
mptcp-olia---static----flyNode03---tmpdmesg.txt 0
mptcp-olia---static----flyNode04---tmpdmesg.txt 0
mptcp-olia---static----gateway---tmpdmesg.txt 292
mptcp-red---static----adhoc01---tmpdmesg.txt 0
mptcp-red---static----adhoc02---tmpdmesg.txt 0
mptcp-red---static----adhoc03---tmpdmesg.txt 0
mptcp-red---static----adhoc04---tmpdmesg.txt 453
mptcp-red---static----adhoc05---tmpdmesg.txt 481
mptcp-red---static----adhoc06---tmpdmesg.txt 494
mptcp-red---static----adhoc07---tmpdmesg.txt 0
mptcp-red---static----adhoc08---tmpdmesg.txt 0
mptcp-red---static----adhoc09---tmpdmesg.txt 0
mptcp-red---static----AP1---tmpdmesg.txt 464
mptcp-red---static----AP2---tmpdmesg.txt 0
mptcp-red---static----flyNode01---tmpdmesg.txt 11
mptcp-red---static----flyNode02---tmpdmesg.txt 1
mptcp-red---static----flyNode03---tmpdmesg.txt 0
mptcp-red---static----flyNode04---tmpdmesg.txt 0
mptcp-red---static----gateway---tmpdmesg.txt 462
mptcp-rr---static----adhoc01---tmpdmesg.txt 20
mptcp-rr---static----adhoc02---tmpdmesg.txt 20
mptcp-rr---static----adhoc03---tmpdmesg.txt 20
mptcp-rr---static----adhoc04---tmpdmesg.txt 210
mptcp-rr---static----adhoc05---tmpdmesg.txt 256
mptcp-rr---static----adhoc06---tmpdmesg.txt 305
mptcp-rr---static----adhoc07---tmpdmesg.txt 0
mptcp-rr---static----adhoc08---tmpdmesg.txt 0
mptcp-rr---static----adhoc09---tmpdmesg.txt 0
mptcp-rr---static----AP1---tmpdmesg.txt 267
mptcp-rr---static----AP2---tmpdmesg.txt 21
mptcp-rr---static----flyNode01---tmpdmesg.txt 49
mptcp-rr---static----flyNode02---tmpdmesg.txt 7
mptcp-rr---static----flyNode03---tmpdmesg.txt 9
mptcp-rr---static----flyNode04---tmpdmesg.txt 9
mptcp-rr---static----gateway---tmpdmesg.txt 287
mptcp-balia---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc04---tmpdmesg.txt 182
mptcp-balia---dynamic1----adhoc05---tmpdmesg.txt 184
mptcp-balia---dynamic1----adhoc06---tmpdmesg.txt 192
mptcp-balia---dynamic1----adhoc07---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-balia---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-balia---dynamic1----AP1---tmpdmesg.txt 179
mptcp-balia---dynamic1----AP2---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode01---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-balia---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-balia---dynamic1----gateway---tmpdmesg.txt 176
mptcp-bbr---dynamic1----adhoc01---tmpdmesg.txt 25
mptcp-bbr---dynamic1----adhoc02---tmpdmesg.txt 25
mptcp-bbr---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-bbr---dynamic1----adhoc04---tmpdmesg.txt 182
mptcp-bbr---dynamic1----adhoc05---tmpdmesg.txt 292
mptcp-bbr---dynamic1----adhoc06---tmpdmesg.txt 358
mptcp-bbr---dynamic1----adhoc07---tmpdmesg.txt 92
mptcp-bbr---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-bbr---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-bbr---dynamic1----AP1---tmpdmesg.txt 210
mptcp-bbr---dynamic1----AP2---tmpdmesg.txt 115
mptcp-bbr---dynamic1----flyNode01---tmpdmesg.txt 9
mptcp-bbr---dynamic1----flyNode02---tmpdmesg.txt 3
mptcp-bbr---dynamic1----flyNode03---tmpdmesg.txt 23
mptcp-bbr---dynamic1----flyNode04---tmpdmesg.txt 70
mptcp-bbr---dynamic1----gateway---tmpdmesg.txt 323
mptcp-blest---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc04---tmpdmesg.txt 249
mptcp-blest---dynamic1----adhoc05---tmpdmesg.txt 441
mptcp-blest---dynamic1----adhoc06---tmpdmesg.txt 458
mptcp-blest---dynamic1----adhoc07---tmpdmesg.txt 7
mptcp-blest---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-blest---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-blest---dynamic1----AP1---tmpdmesg.txt 403
mptcp-blest---dynamic1----AP2---tmpdmesg.txt 7
mptcp-blest---dynamic1----flyNode01---tmpdmesg.txt 182
mptcp-blest---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-blest---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-blest---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-blest---dynamic1----gateway---tmpdmesg.txt 407
mptcp-cubic---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc04---tmpdmesg.txt 201
mptcp-cubic---dynamic1----adhoc05---tmpdmesg.txt 241
mptcp-cubic---dynamic1----adhoc06---tmpdmesg.txt 253
mptcp-cubic---dynamic1----adhoc07---tmpdmesg.txt 27
mptcp-cubic---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-cubic---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-cubic---dynamic1----AP1---tmpdmesg.txt 202
mptcp-cubic---dynamic1----AP2---tmpdmesg.txt 29
mptcp-cubic---dynamic1----flyNode01---tmpdmesg.txt 5
mptcp-cubic---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-cubic---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-cubic---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-cubic---dynamic1----gateway---tmpdmesg.txt 228
mptcp-ecf---dynamic1----adhoc01---tmpdmesg.txt 1
mptcp-ecf---dynamic1----adhoc02---tmpdmesg.txt 1
mptcp-ecf---dynamic1----adhoc03---tmpdmesg.txt 1
mptcp-ecf---dynamic1----adhoc04---tmpdmesg.txt 302
mptcp-ecf---dynamic1----adhoc05---tmpdmesg.txt 332
mptcp-ecf---dynamic1----adhoc06---tmpdmesg.txt 374
mptcp-ecf---dynamic1----adhoc07---tmpdmesg.txt 4
mptcp-ecf---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-ecf---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-ecf---dynamic1----AP1---tmpdmesg.txt 297
mptcp-ecf---dynamic1----AP2---tmpdmesg.txt 14
mptcp-ecf---dynamic1----flyNode01---tmpdmesg.txt 21
mptcp-ecf---dynamic1----flyNode02---tmpdmesg.txt 2
mptcp-ecf---dynamic1----flyNode03---tmpdmesg.txt 10
mptcp-ecf---dynamic1----flyNode04---tmpdmesg.txt 10
mptcp-ecf---dynamic1----gateway---tmpdmesg.txt 308
mptcp-olia---dynamic1----adhoc01---tmpdmesg.txt 2
mptcp-olia---dynamic1----adhoc02---tmpdmesg.txt 1
mptcp-olia---dynamic1----adhoc03---tmpdmesg.txt 1
mptcp-olia---dynamic1----adhoc04---tmpdmesg.txt 167
mptcp-olia---dynamic1----adhoc05---tmpdmesg.txt 168
mptcp-olia---dynamic1----adhoc06---tmpdmesg.txt 178
mptcp-olia---dynamic1----adhoc07---tmpdmesg.txt 0
mptcp-olia---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-olia---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-olia---dynamic1----AP1---tmpdmesg.txt 173
mptcp-olia---dynamic1----AP2---tmpdmesg.txt 0
mptcp-olia---dynamic1----flyNode01---tmpdmesg.txt 6
mptcp-olia---dynamic1----flyNode02---tmpdmesg.txt 6
mptcp-olia---dynamic1----flyNode03---tmpdmesg.txt 0
mptcp-olia---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-olia---dynamic1----gateway---tmpdmesg.txt 171
mptcp-red---dynamic1----adhoc01---tmpdmesg.txt 4
mptcp-red---dynamic1----adhoc02---tmpdmesg.txt 4
mptcp-red---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc04---tmpdmesg.txt 522
mptcp-red---dynamic1----adhoc05---tmpdmesg.txt 573
mptcp-red---dynamic1----adhoc06---tmpdmesg.txt 606
mptcp-red---dynamic1----adhoc07---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-red---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-red---dynamic1----AP1---tmpdmesg.txt 535
mptcp-red---dynamic1----AP2---tmpdmesg.txt 4
mptcp-red---dynamic1----flyNode01---tmpdmesg.txt 12
mptcp-red---dynamic1----flyNode02---tmpdmesg.txt 12
mptcp-red---dynamic1----flyNode03---tmpdmesg.txt 4
mptcp-red---dynamic1----flyNode04---tmpdmesg.txt 4
mptcp-red---dynamic1----gateway---tmpdmesg.txt 536
mptcp-rr---dynamic1----adhoc01---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc02---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc03---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc04---tmpdmesg.txt 330
mptcp-rr---dynamic1----adhoc05---tmpdmesg.txt 339
mptcp-rr---dynamic1----adhoc06---tmpdmesg.txt 343
mptcp-rr---dynamic1----adhoc07---tmpdmesg.txt 2
mptcp-rr---dynamic1----adhoc08---tmpdmesg.txt 0
mptcp-rr---dynamic1----adhoc09---tmpdmesg.txt 0
mptcp-rr---dynamic1----AP1---tmpdmesg.txt 326
mptcp-rr---dynamic1----AP2---tmpdmesg.txt 6
mptcp-rr---dynamic1----flyNode01---tmpdmesg.txt 0
mptcp-rr---dynamic1----flyNode02---tmpdmesg.txt 0
mptcp-rr---dynamic1----flyNode03---tmpdmesg.txt 4
mptcp-rr---dynamic1----flyNode04---tmpdmesg.txt 0
mptcp-rr---dynamic1----gateway---tmpdmesg.txt 330
mptcp-balia---dynamic2----adhoc01---tmpdmesg.txt 23
mptcp-balia---dynamic2----adhoc02---tmpdmesg.txt 19
mptcp-balia---dynamic2----adhoc03---tmpdmesg.txt 8
mptcp-balia---dynamic2----adhoc04---tmpdmesg.txt 239
mptcp-balia---dynamic2----adhoc05---tmpdmesg.txt 250
mptcp-balia---dynamic2----adhoc06---tmpdmesg.txt 366
mptcp-balia---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-balia---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-balia---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-balia---dynamic2----AP1---tmpdmesg.txt 336
mptcp-balia---dynamic2----AP2---tmpdmesg.txt 0
mptcp-balia---dynamic2----flyNode01---tmpdmesg.txt 1
mptcp-balia---dynamic2----flyNode02---tmpdmesg.txt 99
mptcp-balia---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-balia---dynamic2----flyNode04---tmpdmesg.txt 1
mptcp-balia---dynamic2----gateway---tmpdmesg.txt 333
mptcp-bbr---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc02---tmpdmesg.txt 1
mptcp-bbr---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc04---tmpdmesg.txt 67
mptcp-bbr---dynamic2----adhoc05---tmpdmesg.txt 86
mptcp-bbr---dynamic2----adhoc06---tmpdmesg.txt 280
mptcp-bbr---dynamic2----adhoc07---tmpdmesg.txt 54
mptcp-bbr---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-bbr---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-bbr---dynamic2----AP1---tmpdmesg.txt 215
mptcp-bbr---dynamic2----AP2---tmpdmesg.txt 26
mptcp-bbr---dynamic2----flyNode01---tmpdmesg.txt 26
mptcp-bbr---dynamic2----flyNode02---tmpdmesg.txt 150
mptcp-bbr---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-bbr---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-bbr---dynamic2----gateway---tmpdmesg.txt 239
mptcp-blest---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-blest---dynamic2----adhoc02---tmpdmesg.txt 0
mptcp-blest---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-blest---dynamic2----adhoc04---tmpdmesg.txt 104
mptcp-blest---dynamic2----adhoc05---tmpdmesg.txt 112
mptcp-blest---dynamic2----adhoc06---tmpdmesg.txt 131
mptcp-blest---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-blest---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-blest---dynamic2----adhoc09---tmpdmesg.txt 10
mptcp-blest---dynamic2----AP1---tmpdmesg.txt 101
mptcp-blest---dynamic2----AP2---tmpdmesg.txt 0
mptcp-blest---dynamic2----flyNode01---tmpdmesg.txt 2
mptcp-blest---dynamic2----flyNode02---tmpdmesg.txt 2
mptcp-blest---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-blest---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-blest---dynamic2----gateway---tmpdmesg.txt 98
mptcp-cubic---dynamic2----adhoc01---tmpdmesg.txt 18
mptcp-cubic---dynamic2----adhoc02---tmpdmesg.txt 18
mptcp-cubic---dynamic2----adhoc03---tmpdmesg.txt 18
mptcp-cubic---dynamic2----adhoc04---tmpdmesg.txt 249
mptcp-cubic---dynamic2----adhoc05---tmpdmesg.txt 293
mptcp-cubic---dynamic2----adhoc06---tmpdmesg.txt 341
mptcp-cubic---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-cubic---dynamic2----adhoc08---tmpdmesg.txt 9
mptcp-cubic---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-cubic---dynamic2----AP1---tmpdmesg.txt 264
mptcp-cubic---dynamic2----AP2---tmpdmesg.txt 9
mptcp-cubic---dynamic2----flyNode01---tmpdmesg.txt 21
mptcp-cubic---dynamic2----flyNode02---tmpdmesg.txt 1
mptcp-cubic---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-cubic---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-cubic---dynamic2----gateway---tmpdmesg.txt 269
mptcp-ecf---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-ecf---dynamic2----adhoc02---tmpdmesg.txt 41
mptcp-ecf---dynamic2----adhoc03---tmpdmesg.txt 2
mptcp-ecf---dynamic2----adhoc04---tmpdmesg.txt 308
mptcp-ecf---dynamic2----adhoc05---tmpdmesg.txt 310
mptcp-ecf---dynamic2----adhoc06---tmpdmesg.txt 538
mptcp-ecf---dynamic2----adhoc07---tmpdmesg.txt 28
mptcp-ecf---dynamic2----adhoc08---tmpdmesg.txt 3
mptcp-ecf---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-ecf---dynamic2----AP1---tmpdmesg.txt 486
mptcp-ecf---dynamic2----AP2---tmpdmesg.txt 8
mptcp-ecf---dynamic2----flyNode01---tmpdmesg.txt 31
mptcp-ecf---dynamic2----flyNode02---tmpdmesg.txt 214
mptcp-ecf---dynamic2----flyNode03---tmpdmesg.txt 1
mptcp-ecf---dynamic2----flyNode04---tmpdmesg.txt 1
mptcp-ecf---dynamic2----gateway---tmpdmesg.txt 491
mptcp-olia---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-olia---dynamic2----adhoc02---tmpdmesg.txt 11
mptcp-olia---dynamic2----adhoc03---tmpdmesg.txt 8
mptcp-olia---dynamic2----adhoc04---tmpdmesg.txt 119
mptcp-olia---dynamic2----adhoc05---tmpdmesg.txt 137
mptcp-olia---dynamic2----adhoc06---tmpdmesg.txt 232
mptcp-olia---dynamic2----adhoc07---tmpdmesg.txt 0
mptcp-olia---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-olia---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-olia---dynamic2----AP1---tmpdmesg.txt 208
mptcp-olia---dynamic2----AP2---tmpdmesg.txt 1
mptcp-olia---dynamic2----flyNode01---tmpdmesg.txt 12
mptcp-olia---dynamic2----flyNode02---tmpdmesg.txt 30
mptcp-olia---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-olia---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-olia---dynamic2----gateway---tmpdmesg.txt 206
mptcp-red---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc02---tmpdmesg.txt 8
mptcp-red---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc04---tmpdmesg.txt 191
mptcp-red---dynamic2----adhoc05---tmpdmesg.txt 207
mptcp-red---dynamic2----adhoc06---tmpdmesg.txt 265
mptcp-red---dynamic2----adhoc07---tmpdmesg.txt 15
mptcp-red---dynamic2----adhoc08---tmpdmesg.txt 0
mptcp-red---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-red---dynamic2----AP1---tmpdmesg.txt 231
mptcp-red---dynamic2----AP2---tmpdmesg.txt 1
mptcp-red---dynamic2----flyNode01---tmpdmesg.txt 0
mptcp-red---dynamic2----flyNode02---tmpdmesg.txt 29
mptcp-red---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-red---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-red---dynamic2----gateway---tmpdmesg.txt 230
mptcp-rr---dynamic2----adhoc01---tmpdmesg.txt 0
mptcp-rr---dynamic2----adhoc02---tmpdmesg.txt 6
mptcp-rr---dynamic2----adhoc03---tmpdmesg.txt 0
mptcp-rr---dynamic2----adhoc04---tmpdmesg.txt 224
mptcp-rr---dynamic2----adhoc05---tmpdmesg.txt 215
mptcp-rr---dynamic2----adhoc06---tmpdmesg.txt 392
mptcp-rr---dynamic2----adhoc07---tmpdmesg.txt 14
mptcp-rr---dynamic2----adhoc08---tmpdmesg.txt 3
mptcp-rr---dynamic2----adhoc09---tmpdmesg.txt 0
mptcp-rr---dynamic2----AP1---tmpdmesg.txt 314
mptcp-rr---dynamic2----AP2---tmpdmesg.txt 17
mptcp-rr---dynamic2----flyNode01---tmpdmesg.txt 0
mptcp-rr---dynamic2----flyNode02---tmpdmesg.txt 147
mptcp-rr---dynamic2----flyNode03---tmpdmesg.txt 0
mptcp-rr---dynamic2----flyNode04---tmpdmesg.txt 0
mptcp-rr---dynamic2----gateway---tmpdmesg.txt 328
dmptcp---dynamic1----adhoc01---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc02---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc03---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc04---tmpdmesg.txt 204
dmptcp---dynamic1----adhoc05---tmpdmesg.txt 209
dmptcp---dynamic1----adhoc06---tmpdmesg.txt 214
dmptcp---dynamic1----adhoc07---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc08---tmpdmesg.txt 0
dmptcp---dynamic1----adhoc09---tmpdmesg.txt 0
dmptcp---dynamic1----AP1---tmpdmesg.txt 205
dmptcp---dynamic1----AP2---tmpdmesg.txt 0
dmptcp---dynamic1----flyNode01---tmpdmesg.txt 2
dmptcp---dynamic1----flyNode02---tmpdmesg.txt 2
dmptcp---dynamic1----flyNode03---tmpdmesg.txt 0
dmptcp---dynamic1----flyNode04---tmpdmesg.txt 0
dmptcp---dynamic1----gateway---tmpdmesg.txt 203
dmptcp---dynamic2----adhoc01---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc02---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc03---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc04---tmpdmesg.txt 98
dmptcp---dynamic2----adhoc05---tmpdmesg.txt 108
dmptcp---dynamic2----adhoc06---tmpdmesg.txt 119
dmptcp---dynamic2----adhoc07---tmpdmesg.txt 3
dmptcp---dynamic2----adhoc08---tmpdmesg.txt 0
dmptcp---dynamic2----adhoc09---tmpdmesg.txt 0
dmptcp---dynamic2----AP1---tmpdmesg.txt 86
dmptcp---dynamic2----AP2---tmpdmesg.txt 2
dmptcp---dynamic2----flyNode01---tmpdmesg.txt 0
dmptcp---dynamic2----flyNode02---tmpdmesg.txt 0
dmptcp---dynamic2----flyNode03---tmpdmesg.txt 0
dmptcp---dynamic2----flyNode04---tmpdmesg.txt 0
dmptcp---dynamic2----gateway---tmpdmesg.txt 87
dmptcp---static----adhoc01---tmpdmesg.txt 0
dmptcp---static----adhoc02---tmpdmesg.txt 0
dmptcp---static----adhoc03---tmpdmesg.txt 0
dmptcp---static----adhoc04---tmpdmesg.txt 214
dmptcp---static----adhoc05---tmpdmesg.txt 217
dmptcp---static----adhoc06---tmpdmesg.txt 223
dmptcp---static----adhoc07---tmpdmesg.txt 0
dmptcp---static----adhoc08---tmpdmesg.txt 0
dmptcp---static----adhoc09---tmpdmesg.txt 0
dmptcp---static----AP1---tmpdmesg.txt 214
dmptcp---static----AP2---tmpdmesg.txt 0
dmptcp---static----flyNode01---tmpdmesg.txt 0
dmptcp---static----flyNode02---tmpdmesg.txt 0
dmptcp---static----flyNode03---tmpdmesg.txt 0
dmptcp---static----flyNode04---tmpdmesg.txt 0
dmptcp---static----gateway---tmpdmesg.txt 211
